{"name": "test_bas_result_check", "status": "failed", "statusDetails": {"message": "AssertionError: ожидаемый результат не совпадает с полученным\nassert True == False\n  +True\n  -False", "trace": "test_bad_result.py:3: in test_bas_result_check\n    assert True == False, \"ожидаемый результат не совпадает с полученным\"\nE   AssertionError: ожидаемый результат не совпадает с полученным\nE   assert True == False\nE     +True\nE     -False"}, "attachments": [{"name": "log", "source": "4f342dfe-1941-4a84-b87d-082a40740b59-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "6d1d7bff-3746-40c8-beeb-da998d969082-attachment.txt", "type": "text/plain"}], "start": 1596534414089, "stop": 1596534414089, "uuid": "5b8c0a8f-c6dc-479f-872d-a10f85cd9121", "historyId": "b90642ceb2f3b4a90b5166f617bed14a", "testCaseId": "901d9abe59f0ff217281fd5a08fe93da", "fullName": "test_bad_result#test_bas_result_check", "labels": [{"name": "suite", "value": "test_bad_result"}, {"name": "host", "value": "S340"}, {"name": "thread", "value": "5836-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_bad_result"}]}