{"name": "test_bas_result_check", "status": "failed", "statusDetails": {"message": "AssertionError: ожидаемый результат не совпадает с полученным\nassert True == False\n  +True\n  -False", "trace": "test_bad_result.py:3: in test_bas_result_check\n    assert True == False, \"ожидаемый результат не совпадает с полученным\"\nE   AssertionError: ожидаемый результат не совпадает с полученным\nE   assert True == False\nE     +True\nE     -False"}, "attachments": [{"name": "log", "source": "f6e5422d-b3ac-4060-a17d-1e5a97ec3870-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "c97ba7b0-a4aa-4da2-8c87-173c288b7ee0-attachment.txt", "type": "text/plain"}], "start": 1596535568010, "stop": 1596535568010, "uuid": "1b6b0b77-0ba7-4051-bb81-32f7a31043df", "historyId": "b90642ceb2f3b4a90b5166f617bed14a", "testCaseId": "901d9abe59f0ff217281fd5a08fe93da", "fullName": "test_bad_result#test_bas_result_check", "labels": [{"name": "suite", "value": "test_bad_result"}, {"name": "host", "value": "S340"}, {"name": "thread", "value": "7041-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_bad_result"}]}